### ISSUE TITLE
Clang-Format does not recognize keys

### ISSUE THREAD

**Issue by ilendemli** [ebaker355/clang-format#6]
Adding either BreakOnElse: false or BreakBetweenDoWhile: false results in an error saying that the key is unknown: unknown argument.

I replaced the binary in my plugin with yours.

EDIT: Even happens after compiling it by myself.

**Comment by ebaker355** [comment]
@ilendemli If you applied my patch to the latest source, I am aware that the patch is out of date. I have not had the time lately to keep it up to date. Also, there appear to be [other issues](http://stackoverflow.com/questions/30110479/clang-format-stop-breaking-long-methods-up) with clang-format 3.7, which are also present in my custom binary. If those bother you (like they do me), I'd recommend using an older version of clang-format, for now.
